basePath: /
definitions:
  types.Transaction:
    properties:
      amount:
        type: integer
      category:
        type: string
      date:
        type: string
      id:
        type: string
      name:
        type: string
      notes:
        type: string
      transactionType:
        type: string
      userId:
        type: string
    type: object
  types.UpdateUserPayload:
    properties:
      email:
        type: string
      name:
        type: string
      notes:
        type: string
    required:
    - email
    - name
    type: object
  types.User:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      notes:
        type: string
      transaction:
        items:
          $ref: '#/definitions/types.Transaction'
        type: array
    type: object
host: localhost:8080
info:
  contact: {}
  description: Expense Tracking Dashboard
  title: PSP Backend API
  version: "1.0"
paths:
  /user:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/types.User'
            type: array
      summary: Get all Users
      tags:
      - User
    post:
      consumes:
      - application/json
      parameters:
      - description: User to update
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.UpdateUserPayload'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.User'
      summary: Creates a new User
      tags:
      - User
  /user/{userId}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: boolean
      summary: Delete User by Id
      tags:
      - User
    put:
      consumes:
      - application/json
      parameters:
      - description: User to update
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/types.UpdateUserPayload'
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.User'
      summary: Updates User by Id
      tags:
      - User
swagger: "2.0"
